# File: .github/workflows/php.yml

name: PHP Composer & Code Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: دریافت کد (بدون تغییر)
      - uses: actions/checkout@v4

      # مرحله ۲: راه‌اندازی PHP (بدون تغییر)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql

      # مرحله ۳: نصب وابستگی‌ها (بدون تغییر)
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # مرحله ۴: اصلاح استایل کد (تغییر یافته)
      - name: Check & Fix Coding Style (PHP-CS-Fixer)
        # فلگ --dry-run حذف شده تا فایل‌ها واقعاً اصلاح شوند
        run: vendor/bin/php-cs-fixer fix --allow-risky=yes

      # مرحله ۵: کامیت خودکار تغییرات (مرحله جدید)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # پیام کامیتی که ربات ثبت می‌کند
          commit_message: "style: Apply PHP-CS-Fixer coding style fixes"
          # نام کاربری و ایمیل ربات
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          # نویسنده اصلی کامیت (شما که اکشن را فعال کردید)
          commit_author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      # مرحله ۶: اجرای تحلیل استاتیک (بدون تغییر)
      - name: Run Static Analysis (PHPStan)
        run: vendor/bin/phpstan analyse --level=2 admin includes